### ISSUE TITLE
performance tests error in `test_aggregated_bulletproof_plus`

### ISSUE THREAD

**Issue by jeffro256** [UkoeHB/monero#16]
On the sixth and final `test_aggregated_bulletproof_plus` performance test instance [here](https://github.com/UkoeHB/monero/blob/ea9fa079bf0ce0a6d32472801db8d58bfbf0276a/tests/performance_tests/main.cpp#L359-L360C2), an exception is thrown with the message: `sv/gamma are too large`. The assertion statement can be found [here](https://github.com/monero-project/monero/blob/8123d945f874548e87d3850b6633f047120ece45/src/ringct/bulletproofs_plus.cc#L535), but I don't know enough about bulletproofs to debug it.

**Comment by UkoeHB** [comment]
Oh it only allows 16 range proofs to be aggregated, since that's the max number of outputs in ringct. At one point I was perf testing more than that (as you can see, that test is doing 32 aggregated proofs). That test can be deleted.

**Comment by UkoeHB** [comment]
Removed the broken tests.
