### ISSUE TITLE
Edge cases where the Seraphis wallet lib wouldn't identify received legacy enotes that wallet2 does

### ISSUE THREAD

**Issue by j-berman** [UkoeHB/monero#27]
1. When there is >1 tx pub key included in tx extra:
    - wallet2 generates derivations for every tx pub key and checks every derivation against every output in each tx.
        - Source: 
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L2219-L2222
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L3155-L3156
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L3174-L3180
             - https://github.com/monero-project/monero/commit/11ae1873f8cd4e041abf25f08fa4969e75aa8b40
                 - Note: it looks like this commit to scan using every tx pub key was added because there was a bug in cold wallets that used the 2nd pub key.
    - The Seraphis lib only checks the first tx pub key included in tx extra.
       - Source: 
           - [Source 1](https://github.com/UkoeHB/monero/blob/bcae39d2624ecec946f5875e6323ec5a6ba8b115/src/seraphis_core/legacy_core_utils.cpp#L383-L389)
           - [Source 2](https://github.com/UkoeHB/monero/blob/bcae39d2624ecec946f5875e6323ec5a6ba8b115/src/seraphis_main/scan_balance_recovery_utils.cpp#L373-L377)
    - The problem: if someone crafts a non-standard tx using the nth tx pub key (where n > 1), then the Seraphis wallet lib wouldn't identify any receives in the tx but wallet2 would.
    - **The proposed fix**: the Seraphis lib could scan using all tx pub keys in tx extra.

2. When the first additional pub keys vector in tx extra has unequal number of pub keys than there are enotes in the tx:
    - wallet2 generates derivations for each additional pub key, and will then ignore those additional pub keys beyond the number of enotes in the tx and scan the tx normally.
        - Source:
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L2224-L2230
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L3157-L3158
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L3170-L3178
             - https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/cryptonote_basic/cryptonote_format_utils.cpp#L1059-L1063
    - The Seraphis lib doesn't scan the tx.
       - Source:
           - [Source 1](https://github.com/UkoeHB/monero/blob/bcae39d2624ecec946f5875e6323ec5a6ba8b115/src/seraphis_core/legacy_core_utils.cpp#L393-L398)
           - [Source 2](https://github.com/UkoeHB/monero/blob/bcae39d2624ecec946f5875e6323ec5a6ba8b115/src/seraphis_main/scan_balance_recovery_utils.cpp#L373-L384)
    - The problem: if someone crafts a non-standard tx that includes an unequal additional pub keys than enotes in a tx, then the Seraphis wallet lib wouldn't identify any receives in the tx but wallet2 would.
    - **The proposed fix**: if there are more additional pub keys than enotes, the Seraphis lib could ignore the additional pub keys beyond the number of enotes in a tx. If there are fewer additional pub keys than enotes the Seraphis lib could just scan using additionals corresponding to the lower indexed enotes.

**Comment by UkoeHB** [comment]
Fixed in #43
